### ISSUE TITLE
Not enough Padding

### ISSUE THREAD

**Issue by naklic0der** [Project-Club-IIITS/hacktoberfest#7]
White space is one of the most important thing of UI. I feel more padding ( at required places ) can be added to give UI a premium look.

![image](https://user-images.githubusercontent.com/45015876/96283384-c3baba80-0ff9-11eb-86e2-65591d9569f0.png)
![image](https://user-images.githubusercontent.com/45015876/96283411-cb7a5f00-0ff9-11eb-905d-4c9118b1f7b6.png)
![image](https://user-images.githubusercontent.com/45015876/96283444-d9c87b00-0ff9-11eb-88ef-c3f7827a4c08.png)
![image](https://user-images.githubusercontent.com/45015876/96283475-e351e300-0ff9-11eb-99b0-a5c7487f7172.png)
![image](https://user-images.githubusercontent.com/45015876/96283495-e947c400-0ff9-11eb-95fa-82a44759d9f4.png)

**Comment by ram-nad** [comment]
Thanks for taking out the time for pointing out the issues. We are currently busy with organising the event so will be very happy if you can fix these things as well. Thanks again.

If you would like we will assign this issue to you.

**Comment by naklic0der** [comment]
Thank you for the opportunity, but I am quite busy these days.
